version: '2.1'

services:
  nginx:
    build: './'
    networks:
      nginx_network:
    volumes:
      - nginx-volume:/srv/nginx
      - static-volume:/srv/static
    ports:
      - "${SERVER_PORT:-8080}:80"
networks:
  external:
    name: nginx_network
volumes:
  nginx-volume:
  static-volume:
